// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1tOK0OfpbChbYBgq5DafSWLe7aZjeyQ',
    appId: '1:163965345453:web:5917c93a64542f0feaf024',
    messagingSenderId: '163965345453',
    projectId: 'thyrocare-ca7e8',
    authDomain: 'thyrocare-ca7e8.firebaseapp.com',
    storageBucket: 'thyrocare-ca7e8.appspot.com',
    measurementId: 'G-96JJ4WM0BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWWXmUP7TSvyktbyQ0_dnDYwGt_wTGm8',
    appId: '1:163965345453:android:2d93156ff0544c5feaf024',
    messagingSenderId: '163965345453',
    projectId: 'thyrocare-ca7e8',
    storageBucket: 'thyrocare-ca7e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0OX-3_SZ_-C340XSwjodbtdj6HTZHQc',
    appId: '1:163965345453:ios:fa8b0905c6961e7deaf024',
    messagingSenderId: '163965345453',
    projectId: 'thyrocare-ca7e8',
    storageBucket: 'thyrocare-ca7e8.appspot.com',
    iosBundleId: 'com.thyrocare.groot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0OX-3_SZ_-C340XSwjodbtdj6HTZHQc',
    appId: '1:163965345453:ios:97c5aafaf949d048eaf024',
    messagingSenderId: '163965345453',
    projectId: 'thyrocare-ca7e8',
    storageBucket: 'thyrocare-ca7e8.appspot.com',
    iosBundleId: 'com.thyrocare.groot.RunnerTests',
  );
}
