// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeE_-ebpWVSVRcJkMFd8JF5qhGfwDUfxg',
    appId: '1:910092138537:web:ad7eea843a4c8f64294438',
    messagingSenderId: '910092138537',
    projectId: 'thyrocare-8d7e6',
    authDomain: 'thyrocare-8d7e6.firebaseapp.com',
    storageBucket: 'thyrocare-8d7e6.appspot.com',
    measurementId: 'G-YZRVKHMEF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGzIIv5BmXEgSlSZMEiZ-Ha_GIntv6-E',
    appId: '1:910092138537:android:2208866d3426856a294438',
    messagingSenderId: '910092138537',
    projectId: 'thyrocare-8d7e6',
    storageBucket: 'thyrocare-8d7e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUisGcI0Rxwfz9smy8dPhyda_NL9WtRdY',
    appId: '1:910092138537:ios:51ffd2d2b990254a294438',
    messagingSenderId: '910092138537',
    projectId: 'thyrocare-8d7e6',
    storageBucket: 'thyrocare-8d7e6.appspot.com',
    iosBundleId: 'com.example.thyrocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUisGcI0Rxwfz9smy8dPhyda_NL9WtRdY',
    appId: '1:910092138537:ios:d6d559625f35d3f1294438',
    messagingSenderId: '910092138537',
    projectId: 'thyrocare-8d7e6',
    storageBucket: 'thyrocare-8d7e6.appspot.com',
    iosBundleId: 'com.example.thyrocare.RunnerTests',
  );
}
